YEAR = "2022"
SEMESTER = "1"  # 1: Otoño, 2: Primavera, 3: Verano

DEPTS = {  # id: [Cód, Nombre]
    "12060003": ["AA", "Área para el Aprendizaje de la Ingeniería y Ciencias A2IC"],
    "3": ["AS", "Departamento de Astronomía"],
    "5": ["CC", "Departamento de Ciencias de la Computación"],
    "6": ["CI", "Departamento de Ingeniería Civil"],
    "306": ["CM", "Departamento de Ciencia de los Materiales"],
    "7": ["DR", "Área de Deportes, Recreación y Cultura"],
    "305": ["ED", "Doctorado en Ingeniería Eléctrica"],
    "8": ["EH", "Estudios Transversales en Humanidades para las Ingenierías y Ciencias"],
    "9": ["EI", "Área de Idiomas, Escuela de Ingeniería"],
    "12060002": ["EI", "Área de Ingeniería e Innovación"],
    "27": ["EI", "Escuela de Ingeniería"],
    "10": ["EL", "Departamento de Ingeniería Eléctrica"],
    "303": ["EP", "Escuela de Postgrado"],
    "12": ["ES", "Escuela de Ingeniería y Ciencias"],
    "310": ["FG", "Plataforma"],
    "13": ["FI", "Departamento de Física"],
    "15": ["GF", "Departamento de Geofísica"],
    "16": ["GL", "Departamento de Geología"],
    "19": ["IN", "Departamento de Ingeniería Industrial"],
    "21": ["MA", "Departamento de Ingeniería Matemática"],
    "22": ["ME", "Departamento de Ingeniería Mecánica"],
    "23": ["MI", "Departamento de Ingeniería de Minas"],
    "24": ["MT", "Doctorado en Ciencia de los Materiales"],
    "307": ["QB", "Departamento de Ingeniería Química y Biotecnología"],
}

CODIGO_DEPTS = {
	"AA": ["12060003"],
	"AS": ["3"],
	"CC": ["5"],
	"CI": ["6"],
	"CM": ["306"],
	"DR": ["7"],
	"ED": ["305"],
	"EH": ["8"],
	"EI": ["12060002","9"],
	"EL": ["10"],
	"EP": ["303"],
	"ES": ["12"],
	"FG": ["310"],
	"FI": ["13"],
	"GF": ["15"],
	"GL": ["16"],
	"IN": ["19"],
	"MA": ["21"],
	"ME": ["22"],
	"MI": ["23"],
	"MT": ["24"],
	"QB": ["307"],
}
